services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynet
    command: --default-authentication-plugin=mysql_native_password

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-container
    command: -url=jdbc:mysql://${DB_HOST}/${MYSQL_DATABASE} -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} -locations=filesystem:/flyway/sql -connectRetries=10 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql
    networks:
      - mynet

  java-app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: java-app-container
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mynet

volumes:
  mysql-data:

networks:
  mynet:
    driver: bridge
